#!/bin/sh -
case $GIT_CEILING_DIRECTORIES in '')
    GIT_CEILING_DIRECTORIES=~ exec /usr/bin/exa --color=always "$@"
esac
GIT_CEILING_DIRECTORIES=~:$GIT_CEILING_DIRECTORIES \
    exec /usr/bin/exa --color=always "$@"
