#!/usr/bin/osascript

on run arguments
    set command to {" cd " & quoted form of (do shell script "pwd")}
    if length of arguments > 0 then
        set end of command to " &&"
    end if
    repeat with argument in arguments
        set end of command to space & quoted form of argument
    end repeat

    tell application "Terminal"
        do script command as string
    end tell
end run
